# Лабораторная работа №2


$$
AB =
\begin{bmatrix}

2746 & 9890 & 8115 & 7101 & 8857 & 3676 & 4731 & 1740 & 1800 & 3877 & 3871\\
2537 & 5625 & 7033 & 1509 & 3556 & 6529 & 8267 & 7645 & 9001 & 9094 & 2002\\
9690 & 2436 & 8071 & 2027 & 6786 & 8996 & 9490 & 1633 & 3647 & 9890 & 3581\\
8409 & 8432 & 3736 & 2438 & 6625 & 6387 & 5961 & 4005 & 5829 & 2660 & 3658\\
8611 & 7671 & 1704 & 3857 & 7934 & 9888 & 1711 & 1055 & 3071 & 7667 & 4139\\
2465 & 5098 & 4908 & 2944 & 7810 & 1914 & 8558 & 7504 & 6315 & 9582 & 5191\\
3727 & 2243 & 5256 & 7755 & 7905 & 5692 & 4525 & 1227 & 2173 & 9201 & 1011\\
4940 & 3757 & 6081 & 5575 & 5955 & 3783 & 7946 & 7318 & 5700 & 5278 & 7808\\
6787 & 4257 & 5467 & 5257 & 5911 & 6624 & 1018 & 8178 & 8756 & 7427 & 7835\\
3597 & 5027 & 6818 & 3040 & 3830 & 3972 & 1601 & 9346 & 7335 & 1680 & 9481\\
\end{bmatrix}
$$

# Подготовка

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import scipy as sp

In [3]:
a = np.array([[2746, 9890, 8115, 7101, 8857, 3676, 4731, 1740, 1800, 3877],
             [2537, 5625, 7033, 1509, 3556, 6529, 8267, 7645, 9001, 9094],
             [9690, 2436, 8071, 2027, 6786, 8996, 9490, 1633, 3647, 9890],
             [8409, 8432, 3736, 2438, 6625, 6387, 5961, 4005, 5829, 2660],
             [8611, 7671, 1704, 3857, 7934, 9888, 1711, 1055, 3071, 7667],
             [2465, 5098, 4908, 2944, 7810, 1914, 8558, 7504, 6315, 9582],
             [3727, 2243, 5256, 7755, 7905, 5692, 4525, 1227, 2173, 9201],
             [4940, 3757, 6081, 5575, 5955, 3783, 7946, 7318, 5700, 5278],
             [6787, 4257, 5467, 5257, 5911, 6624, 1018, 8178, 8756, 7427],
             [3597, 5027, 6818, 3040, 3830, 3972, 1601, 9346, 7335, 1680]])


b = np.array([3871, 2002, 3581, 3658, 4139, 5191, 1011, 7808, 7835, 9481]).reshape(10, 1)
deta = np.linalg.det(a)


Если матрица вырождена, к первому элементу прибавляется 1

In [4]:
if deta == 0:
    a[0][0] += 1

# Решение 1

Используем библиотеку scipy, модуль linalg

In [5]:
x = sp.linalg.solve(a, b)
for i in range(10):
    
    print("x"+ str(i) + " =", x[i][0])

x0 = 1.1642121787066364
x1 = 0.5588401422677944
x2 = 0.25972606088497363
x3 = 0.21583091684285172
x4 = -0.8209909970516509
x5 = -0.4240083788217738
x6 = -0.33851328054963464
x7 = 2.0933690964603717
x8 = -2.044030885096305
x9 = 0.5094980094682421


# Решение 2

Решение через обратную матрицу

In [10]:
ainv = np.linalg.inv(a)
x = np.matmul(ainv, b)
for i in range(10):
    
    print("x"+ str(i) + " =", x[i][0])

x0 = 1.1642121787066353
x1 = 0.5588401422677944
x2 = 0.25972606088497463
x3 = 0.21583091684285016
x4 = -0.8209909970516494
x5 = -0.42400837882177267
x6 = -0.33851328054963536
x7 = 2.0933690964603717
x8 = -2.044030885096305
x9 = 0.5094980094682422


# Решение 3


### Решение с помощью метода Гаусса. Сначала матрица приводится к треугольному виду типа
$$\begin{bmatrix}
a & b & c & ... & n1\\
0 & d & e & ... & n2\\
... &... & ... & ... & ...\\
0 & 0 & 0 & ... & nn
\end{bmatrix}

Подготовка матрицы

In [7]:
a = np.array([ [2746.0, 9890.0, 8115.0, 7101.0, 8857.0, 3676.0, 4731.0, 1740.0, 1800.0, 3877.0, 3871.0],
               [2537.0, 5625.0, 7033.0, 1509.0, 3556.0, 6529.0, 8267.0, 7645.0, 9001.0, 9094.0, 2002.0],
               [9690.0, 2436.0, 8071.0, 2027.0, 6786.0, 8996.0, 9490.0, 1633.0, 3647.0, 9890.0, 3581.0],
               [8409.0, 8432.0, 3736.0, 2438.0, 6625.0, 6387.0, 5961.0, 4005.0, 5829.0, 2660.0, 3658.0],
               [8611.0, 7671.0, 1704.0, 3857.0, 7934.0, 9888.0, 1711.0, 1055.0, 3071.0, 7667.0, 4139.0],
               [2465.0, 5098.0, 4908.0, 2944.0, 7810.0, 1914.0, 8558.0, 7504.0, 6315.0, 9582.0, 5191.0],
               [3727.0, 2243.0, 5256.0, 7755.0, 7905.0, 5692.0, 4525.0, 1227.0, 2173.0, 9201.0, 1011.0],
               [4940.0, 3757.0, 6081.0, 5575.0, 5955.0, 3783.0, 7946.0, 7318.0, 5700.0, 5278.0, 7808.0],
               [6787.0, 4257.0, 5467.0, 5257.0, 5911.0, 6624.0, 1018.0, 8178.0, 8756.0, 7427.0, 7835.0],
               [3597.0, 5027.0, 6818.0, 3040.0, 3830.0, 3972.0, 1601.0, 9346.0, 7335.0, 1680.0, 9481.0]])


## Визуально красивое решение

Наглядное решение, на основе которого была написана следующая программа

In [8]:
for i in range(9):
    if a[i][i] == 0:
        print("Матрица вырождена")
    else:
        for j in range(i + 1, 10):
            mult = a[j][i] / a[i][i]
            for k in range(11):
                a[j][k] = a[j][k] - a[i][k]*mult
ans = np.zeros((10, 1))
x9 = a[9][10] / a[9][9]
x8 = (a[8][10] - a[8][9] * x9) / a[8][8]
x7 = (a[7][10] - a[7][9] * x9 - a[7][8] * x8)/a[7][7]
x6 = (a[6][10] - a[6][9] * x9 - a[6][8] * x8 - a[6][7] * x7)/a[6][6]
x5 = (a[5][10] - a[5][9] * x9 - a[5][8] * x8 - a[5][7] * x7 - a[5][6] * x6)/a[5][5]
x4 = (a[4][10] - a[4][9] * x9 - a[4][8] * x8 - a[4][7] * x7 - a[4][6] * x6 - a[4][5] * x5)/a[4][4]
x3 = (a[3][10] - a[3][9] * x9 - a[3][8] * x8 - a[3][7] * x7 - a[3][6] * x6 - a[3][5] * x5 - a[3][4] * x4)/a[3][3]
x2 = (a[2][10] - a[2][9] * x9 - a[2][8] * x8 - a[2][7] * x7 - a[2][6] * x6 - a[2][5] * x5 - a[2][4] * x4 - a[2][3] * x3)/a[2][2]
x1 = (a[1][10] - a[1][9] * x9 - a[1][8] * x8 - a[1][7] * x7 - a[1][6] * x6 - a[1][5] * x5 - a[1][4] * x4 - a[1][3] * x3 - a[1][2] * x2)/a[1][1]
x0 = (a[0][10] - a[0][9] * x9 - a[0][8] * x8 - a[0][7] * x7 - a[0][6] * x6 - a[0][5] * x5 - a[0][4] * x4 - a[0][3] * x3 - a[0][2] * x2 - a[0][1] * x1)/a[0][0]
print(x0)
print(x1)
print(x2)
print(x3)
print(x4)
print(x5)
print(x6)
print(x7)
print(x8)
print(x9)

1.1642121787066286
0.558840142267796
0.25972606088497224
0.21583091684284778
-0.8209909970516501
-0.42400837882176307
-0.33851328054963403
2.093369096460382
-2.04403088509632
0.5094980094682432


## Решение короче


In [16]:
x = np.zeros((10, 10))
for i in range(9, -1, -1):
    eq = a[i][10]
    for j in range(9, i-1, -1):
        eq -= a[i][j] * x[j][j]
    x[i][i] = eq / a[i][i]
for i in range(10):
    print("x" + str(i) + " = " + str(x[i][i]))

x0 = 1.161297007716756
x1 = 0.556922303740853
x2 = 0.2598644199251041
x3 = 0.21396774116146583
x4 = -0.816967056379081
x5 = -0.4213203362343699
x6 = -0.3388060390161765
x7 = 2.0917863956922256
x8 = -2.0418924093686504
x9 = 0.5076084487849194


# Решение 4 (не получилось)

In [ ]:
a = np.array([[2746, 9890, 8115, 7101, 8857, 3676, 4731, 1740, 1800, 3877, 3871],
             [2537, 5625, 7033, 1509, 3556, 6529, 8267, 7645, 9001, 9094, 2002],
             [9690, 2436, 8071, 2027, 6786, 8996, 9490, 1633, 3647, 9890, 3581],
             [8409, 8432, 3736, 2438, 6625, 6387, 5961, 4005, 5829, 2660, 3658],
             [8611, 7671, 1704, 3857, 7934, 9888, 1711, 1055, 3071, 7667, 4139],
             [2465, 5098, 4908, 2944, 7810, 1914, 8558, 7504, 6315, 9582, 5191],
             [3727, 2243, 5256, 7755, 7905, 5692, 4525, 1227, 2173, 9201, 1011],
             [4940, 3757, 6081, 5575, 5955, 3783, 7946, 7318, 5700, 5278, 7808],
             [6787, 4257, 5467, 5257, 5911, 6624, 1018, 8178, 8756, 7427, 7835],
             [3597, 5027, 6818, 3040, 3830, 3972, 1601, 9346, 7335, 1680, 9481]])


In [ ]:
a = np.array([[2746, 9890, 8115, 7101, 8857, 3676, 4731, 1740, 1800, 3877],
             [2537, 5625, 7033, 1509, 3556, 6529, 8267, 7645, 9001, 9094],
             [9690, 2436, 8071, 2027, 6786, 8996, 9490, 1633, 3647, 9890],
             [8409, 8432, 3736, 2438, 6625, 6387, 5961, 4005, 5829, 2660],
             [8611, 7671, 1704, 3857, 7934, 9888, 1711, 1055, 3071, 7667],
             [2465, 5098, 4908, 2944, 7810, 1914, 8558, 7504, 6315, 9582],
             [3727, 2243, 5256, 7755, 7905, 5692, 4525, 1227, 2173, 9201],
             [4940, 3757, 6081, 5575, 5955, 3783, 7946, 7318, 5700, 5278],
             [6787, 4257, 5467, 5257, 5911, 6624, 1018, 8178, 8756, 7427],
             [3597, 5027, 6818, 3040, 3830, 3972, 1601, 9346, 7335, 1680]])


ab = np.array([[2746.0, 9890.0, 8115.0, 7101.0, 8857.0, 3676.0, 4731.0, 1740.0, 1800.0, 3877.0, 3871.0],
               [2537.0, 5625.0, 7033.0, 1509.0, 3556.0, 6529.0, 8267.0, 7645.0, 9001.0, 9094.0, 2002.0],
               [9690.0, 2436.0, 8071.0, 2027.0, 6786.0, 8996.0, 9490.0, 1633.0, 3647.0, 9890.0, 3581.0],
               [8409.0, 8432.0, 3736.0, 2438.0, 6625.0, 6387.0, 5961.0, 4005.0, 5829.0, 2660.0, 3658.0],
               [8611.0, 7671.0, 1704.0, 3857.0, 7934.0, 9888.0, 1711.0, 1055.0, 3071.0, 7667.0, 4139.0],
               [2465.0, 5098.0, 4908.0, 2944.0, 7810.0, 1914.0, 8558.0, 7504.0, 6315.0, 9582.0, 5191.0],
               [3727.0, 2243.0, 5256.0, 7755.0, 7905.0, 5692.0, 4525.0, 1227.0, 2173.0, 9201.0, 1011.0],
               [4940.0, 3757.0, 6081.0, 5575.0, 5955.0, 3783.0, 7946.0, 7318.0, 5700.0, 5278.0, 7808.0],
               [6787.0, 4257.0, 5467.0, 5257.0, 5911.0, 6624.0, 1018.0, 8178.0, 8756.0, 7427.0, 7835.0],
               [3597.0, 5027.0, 6818.0, 3040.0, 3830.0, 3972.0, 1601.0, 9346.0, 7335.0, 1680.0, 9481.0]])

In [63]:
def f(b, n):
    for j in range(10):
        b[j][n] = ab[j][10]
    return(b)

deta = np.linalg.det(a)
for i in range(10):
    a1 = a.copy()
    abx = f(a1, i)
    print(abx)
    '''
    detx = np.linalg.det(abx)
    print("x" + str(i) + " = " + str(detx/deta))
    '''


[[3869 3869 3869 3869 3869 3869 3869 3869 3869 3869]
 [2000 2000 2000 2000 2000 2000 2000 2000 2000 2000]
 [3579 3579 3579 3579 3579 3579 3579 3579 3579 3579]
 [3656 3656 3656 3656 3656 3656 3656 3656 3656 3656]
 [4137 4137 4137 4137 4137 4137 4137 4137 4137 4137]
 [5189 5189 5189 5189 5189 5189 5189 5189 5189 5189]
 [1009 1009 1009 1009 1009 1009 1009 1009 1009 1009]
 [7806 7806 7806 7806 7806 7806 7806 7806 7806 7806]
 [7833 7833 7833 7833 7833 7833 7833 7833 7833 7833]
 [9479 9479 9479 9479 9479 9479 9479 9479 9479 9479]]
[[3869 3869 3869 3869 3869 3869 3869 3869 3869 3869]
 [2000 2000 2000 2000 2000 2000 2000 2000 2000 2000]
 [3579 3579 3579 3579 3579 3579 3579 3579 3579 3579]
 [3656 3656 3656 3656 3656 3656 3656 3656 3656 3656]
 [4137 4137 4137 4137 4137 4137 4137 4137 4137 4137]
 [5189 5189 5189 5189 5189 5189 5189 5189 5189 5189]
 [1009 1009 1009 1009 1009 1009 1009 1009 1009 1009]
 [7806 7806 7806 7806 7806 7806 7806 7806 7806 7806]
 [7833 7833 7833 7833 7833 7833 7833 7833 783